#! /bin/sh

# Restart shell
alias exs="exec $SHELL"

# Git
alias gcd='git checkout develop'
alias gpod='git pull origin develop'
alias gs='git status --short'
alias gsl='git status'
alias gd='git diff'
alias gdc='git diff --cached'

# Displays your current directory how it ought to be shown:
# -A : print all files except ./ and ../
# -l : show detailed file information
# -t : sort by time-last-modified
# -r : reverse the sort, to show most recent on bottom
# -h : show file sizes in human-readable format
# -G : colorize the output
alias ll='ls -AltrhG'

alias grep='grep --color=auto --exclude=*.pyc --exclude-dir=.git'

alias vim='NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim'
alias v="$VISUAL"

# clipboard
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
