#! /bin/sh

ch () {
    curl cheat.sh/"$1";
}

# Restore a postgres database given the filename
pgrest () {
    : ${DB_NAME:?'DB_NAME not set'};

    if [[ -f "$1" ]]; then
        dropdb "$DB_NAME";
        createdb "$DB_NAME";
        pg_restore -Fc --no-privileges --no-owner -d "$DB_NAME" "$1";
    else
        echo "File ${1} not found.";
    fi
}

# Open the latest report
or () {
    open "$(find $HOME/Downloads/ -name 'report (*' | sort -t \( -g -k 2 | tail -1)";
}

pf () {
    pip freeze | grep -i "$1"
}

# Move the latest file in ~/Downloads to a given location
function mvd() {
    unset -v latest
    for file in "$HOME/Downloads"/*; do
        [[ $file -nt $latest ]] && latest=$file
    done
    mv -v "$latest" "$1"
}

function upnvim ()
{
    wget -P /tmp/ "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
    mv /tmp/nvim.appimage ~/.local/bin/
    chmod +x ~/.local/bin/nvim.appimage
}

function catsh () {
    cat "$1" | ./src/manage.py shell_plus --quiet-load
}
