#! /bin/sh

# bash-git-prompt
GIT_PROMPT_ONLY_IN_REPO=1
source $HOME/.bash-git-prompt/gitprompt.sh

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Virtualenvwrapper
eval "$(pyenv virtualenv-init -)"
export WORKON_HOME=$HOME/.pyenv/versions
export PROJECT_HOME=$HOME/repos
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
source /usr/local/bin/virtualenvwrapper.sh

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Blackbox
export GPG=gpg2

# gpg-agent
eval $(gpg-agent --daemon --allow-preset-passphrase)

export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
  export VISUAL="nvr -cc tabedit --remote-wait +'set bufhidden=wipe'"
  export EDITOR="$VISUAL"
  export GIT_EDITOR="$EDITOR"
else
  export VISUAL="nvim"
fi
alias v="$VISUAL"

export BAT_THEME="GitHub"
alias cat='bat'
alias catr="fzf --preview 'bat --color \"always\" --style \"full\" {}'"

# fzf-marks
source $HOME/repos/fzf-marks/fzf-marks.plugin.bash
