#! /bin/sh

bind "set completion-ignore-case on"
bind "set completion-prefix-display-length 2"
bind "set show-all-if-ambiguous on"
bind "set show-all-if-unmodified on"
bind "set completion-map-case on"
bind Space:magic-space # pressing space after a history command like !! will expand the command

# vi-mode
set -o vi
bind -m vi-insert '"\C-l": clear-screen'

# Show vi-mode
bind 'set show-mode-in-prompt on'
bind 'set vi-ins-mode-string \1\e[34;1m\2+\1\e[0m\2'
bind 'set vi-cmd-mode-string \1\e[35;1m\2:\1\e[0m\'

# Allow highlighting in less
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export PATH=/usr/local/bin/myfunctions:/usr/local/bin/blackbox:/usr/local/bin:$PATH
export VISUAL=nvim
export EDITOR="$VISUAL"
export GIT_EDITOR="$EDITOR"

export XDG_CONFIG_HOME=$HOME/.config

# Recursive globs with **
shopt -s globstar

# ctrl-s for reverse-i-search 
stty -ixon
