#! /bin/sh

if [ -t 1 ]
then
    bind "set completion-ignore-case on"
    bind "set completion-prefix-display-length 2"
    bind "set show-all-if-ambiguous on"
    bind "set show-all-if-unmodified on"
    bind "set completion-map-case on"
fi

# vi-mode
set -o vi

# Reminder: get list of bindings with `bind -p`
bind -m vi-insert '"\C-l": clear-screen'
bind -m vi-insert '"\C-p": history-substring-search-backward'
bind -m vi-insert '"\C-n": history-substring-search-forward'
bind -m vi-insert '"\C-a": beginning-of-line'
bind -m vi-insert '"\C-e": end-of-line'

# Show vi-mode
bind 'set show-mode-in-prompt on'
bind 'set vi-ins-mode-string \1\e[34;1m\2+\1\e[0m\2'
bind 'set vi-cmd-mode-string \1\e[35;1m\2:\1\e[0m\'
bind Space:magic-space # pressing space after a history command like !! will expand the command

# Allow highlighting in less
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export PATH=/home/alex/.local/bin:usr/local/bin/myfunctions:/usr/local/bin/blackbox:/usr/local/bin:$PATH
export VISUAL=nvim
export EDITOR="$VISUAL"
export GIT_EDITOR="$EDITOR"
export MANPAGER="nvim -c 'set ft=man' -"

export XDG_CONFIG_HOME=$HOME/.config

# Recursive globs with **
shopt -s globstar

# ctrl-s for reverse-i-search 
[[ $- == *i* ]] && stty -ixon

