#! /bin/sh

bind "set completion-ignore-case on"
bind "set completion-prefix-display-length 2"
bind "set show-all-if-ambiguous on"
bind "set show-all-if-unmodified on"
bind "set completion-map-case on"
bind Space:magic-space # pressing space after a history command like !! will expand the command

# Allow highlighting in less
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export PATH=/usr/local/bin/myfunctions:/usr/local/bin/blackbox:/usr/local/bin:$PATH
export EDITOR=nvim

# Recursive globs with **
shopt -s globstar
